version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deployscripts/removeFiles.sh
      timeout: 300
      runas: root
  # AfterInstall:
  #   - location: scripts/change_permissions.sh
  #     timeout: 300
  #     runas: root
  # ApplicationStart:
  #   - location: scripts/appstart.sh
  #     timeout: 300
  #     runas: root
  # ApplicationStop:
  #   - location: scripts/appstop.sh
  #     timeout: 300
  #     runas: root